### ISSUE TITLE
Figure out how many requests per second result from each event type, per validator

### ISSUE THREAD

**Issue by edd** [vegaprotocol/ethereum-event-forwarder#1]
Context: https://github.com/vegaprotocol/devops-infra/issues/707

The old implementation of the event queue was hitting an Infura rate limit. No finger pointing here - this incentive is the first time we’ve had a decent number of people depositing and withdrawing at once, and it has highlighted a weakness. While there are other mitigations for this, it would be interesting to know for the future if we had left our config as it was, if we’d have hit the same limit?

tl;dr: come up with a rough estimate of ETH node requests per second the new bridge uses. This information may be useful to other validators.

# Tasks (suggestion)
- [ ] Create a deposit on Ethereum, log the number of requests to Ethereum this causes
- [ ] Create a withdrawal on Ethereum, log the number of requests to Ethereum this causes
- [ ] Log over an hour how many requests the new event forwarder makes to Ethereum
- [ ] Work out how this scales with 1 deposit/second, 2 deposits/second, etc.

The max we saw in the inventive was around 5 in a block.

# Output
- We should be able to put a number on roughly how many Ethereum requests a day someone can expect to be making while running a validator. This is obviously totally dependent on traffic, but will help guide someone in making infrastructure choices.

**Comment by ValentinTrinque** [comment]
This project is deprecated and no longer supported, because it is now part of the Vega core node.
